window.menuData = [
  {
    id: "tomato-beef-rice",
    name: "番茄肥牛饭",
    category: "盖饭",
    description: "酸甜开胃，肉香和米饭很搭，适合工作日快速开饭。",
    ingredients: ["肥牛卷 250g", "番茄 2 个", "洋葱半个", "米饭 2 碗", "生抽", "蚝油"],
    tags: ["酸甜", "下饭", "工作日晚餐"],
    difficulty: "简单",
    time: 25,
    servings: "2 人份",
    spice: "不辣",
    calories: "中等",
    rating: 5,
    image: "",
    accent: "linear-gradient(135deg, rgba(242, 132, 81, 0.92), rgba(76, 27, 16, 0.48))",
    steps: [
      "番茄切块，洋葱切丝，肥牛焯水 10 秒捞出。",
      "热锅下少量油，炒香洋葱后放入番茄压出汁水。",
      "加入生抽、蚝油和少量清水煮开，再放回肥牛卷翻匀。",
      "汤汁浓稠后浇在热米饭上即可。"
    ],
    tips: "如果想更浓郁，可以最后加一小块黄油提香。"
  },
  {
    id: "garlic-butter-toast",
    name: "蒜香法棍",
    category: "轻食",
    description: "外脆里软，蒜香和黄油香气明显，适合搭配汤或沙拉。",
    ingredients: ["法棍", "蒜末", "黄油", "欧芹碎", "海盐"],
    tags: ["烘烤", "轻食", "入门"],
    difficulty: "简单",
    time: 15,
    servings: "2-3 人份",
    spice: "不辣",
    calories: "偏低",
    rating: 4,
    image: "",
    accent: "linear-gradient(135deg, rgba(255, 202, 133, 0.92), rgba(66, 42, 18, 0.46))",
    steps: [
      "黄油室温软化后和蒜末、欧芹碎、海盐混合均匀。",
      "法棍对半切开，表面均匀抹上蒜香黄油。",
      "烤箱 200 度预热，烤 8 到 10 分钟至表面金黄。",
      "切段装盘，趁热吃口感最好。"
    ],
    tips: "没有烤箱的话，也可以用平底锅小火煎到表面酥脆。"
  },
  {
    id: "portuguese-chicken",
    name: "葡式咖喱鸡",
    category: "主菜",
    description: "椰香浓郁，酱汁适合拌饭，层次感强但步骤不复杂。",
    ingredients: ["鸡腿肉 400g", "土豆", "椰浆", "洋葱", "咖喱块", "牛奶"],
    tags: ["浓郁", "咖喱", "拌饭"],
    difficulty: "中等",
    time: 40,
    servings: "3 人份",
    spice: "微辣",
    calories: "中等",
    rating: 5,
    image: "",
    accent: "linear-gradient(135deg, rgba(255, 155, 95, 0.92), rgba(107, 43, 10, 0.46))",
    steps: [
      "鸡腿肉去骨切块，土豆去皮切滚刀块，洋葱切丁。",
      "炒香洋葱后放入鸡腿肉煎到微黄，再放土豆翻炒。",
      "加入热水没过食材，煮 12 分钟后放咖喱块和椰浆。",
      "最后加少量牛奶调和口感，小火收汁即可。"
    ],
    tips: "搭配米饭或意面都不错，提前一晚炖好第二天味道更融合。"
  },
  {
    id: "salted-beef-rice",
    name: "葱香酱牛肉饭",
    category: "盖饭",
    description: "偏中式风味，酱香突出，适合想吃肉又想快手解决一餐。",
    ingredients: ["酱牛肉", "小葱", "米饭", "糖心蛋", "生抽", "黑胡椒"],
    tags: ["肉香", "快手", "高满足"],
    difficulty: "简单",
    time: 20,
    servings: "2 人份",
    spice: "不辣",
    calories: "中高",
    rating: 4,
    image: "",
    accent: "linear-gradient(135deg, rgba(187, 123, 86, 0.92), rgba(62, 26, 13, 0.44))",
    steps: [
      "小葱切碎，酱牛肉切薄片备用。",
      "锅中少油炒香葱白，加入少量生抽和糖调汁。",
      "放入酱牛肉快速翻热，避免煮老。",
      "铺在米饭上，撒葱花和黑胡椒，配糖心蛋即可。"
    ],
    tips: "如果准备做便当，这道菜放凉以后也很好吃。"
  },
  {
    id: "corn-tuna-toast",
    name: "金枪鱼玉米吐司",
    category: "轻食",
    description: "清爽不腻，适合早餐或下午加餐，也方便提前备料。",
    ingredients: ["吐司 4 片", "金枪鱼罐头", "玉米粒", "沙拉酱", "黑胡椒"],
    tags: ["早餐", "轻食", "低门槛"],
    difficulty: "简单",
    time: 12,
    servings: "2 人份",
    spice: "不辣",
    calories: "偏低",
    rating: 4,
    image: "",
    accent: "linear-gradient(135deg, rgba(255, 213, 143, 0.92), rgba(75, 52, 18, 0.42))",
    steps: [
      "金枪鱼沥干，和玉米粒、沙拉酱、黑胡椒拌匀。",
      "混合馅料铺在吐司表面，厚薄尽量均匀。",
      "可直接食用，也可放进空气炸锅 180 度加热 5 分钟。",
      "切块后装盘，适合配牛奶或咖啡。"
    ],
    tips: "喜欢更有层次的话，可以加一片芝士一起烤。"
  },
  {
    id: "shrimp-sandwich",
    name: "滑蛋虾仁三明治",
    category: "轻食",
    description: "奶香柔和，虾仁口感弹，做法精致但整体不难。",
    ingredients: ["吐司", "鸡蛋 3 个", "虾仁", "黄油", "沙拉酱", "黑胡椒"],
    tags: ["早午餐", "奶香", "高颜值"],
    difficulty: "中等",
    time: 22,
    servings: "2 人份",
    spice: "不辣",
    calories: "中等",
    rating: 5,
    image: "",
    accent: "linear-gradient(135deg, rgba(255, 170, 122, 0.92), rgba(69, 30, 17, 0.44))",
    steps: [
      "虾仁焯熟后切小块，鸡蛋加少量牛奶打散。",
      "小火炒滑蛋，保持湿润状态后关火。",
      "吐司煎香，抹一层薄薄沙拉酱，铺滑蛋和虾仁。",
      "对角切开后压紧定型即可。"
    ],
    tips: "滑蛋不要炒太老，否则夹心会偏干。"
  },
  {
    id: "red-braised-beef",
    name: "红烧牛肉",
    category: "主菜",
    description: "更适合多人一起吃，酱香厚重，属于耐吃型硬菜。",
    ingredients: ["牛腩 500g", "胡萝卜", "八角", "姜片", "冰糖", "生抽", "老抽"],
    tags: ["硬菜", "炖煮", "适合多人"],
    difficulty: "中等",
    time: 70,
    servings: "3-4 人份",
    spice: "不辣",
    calories: "中高",
    rating: 5,
    image: "",
    accent: "linear-gradient(135deg, rgba(190, 86, 63, 0.92), rgba(54, 20, 16, 0.46))",
    steps: [
      "牛腩切块焯水，胡萝卜切滚刀块备用。",
      "锅中炒糖色后放牛腩翻匀，加入姜片和香料。",
      "加生抽、老抽和热水，小火炖 50 分钟。",
      "放入胡萝卜再炖 15 分钟，大火略收汁。"
    ],
    tips: "可以一次多做一点，第二顿拿来拌面也很合适。"
  },
  {
    id: "tofu-claypot",
    name: "葱烧豆腐",
    category: "家常菜",
    description: "非常适合凑一桌菜，口味温和但很下饭，备料简单。",
    ingredients: ["北豆腐", "小葱", "蒜末", "蚝油", "生抽", "淀粉水"],
    tags: ["素菜", "家常", "省时"],
    difficulty: "简单",
    time: 18,
    servings: "2-3 人份",
    spice: "不辣",
    calories: "偏低",
    rating: 4,
    image: "",
    accent: "linear-gradient(135deg, rgba(242, 201, 126, 0.92), rgba(73, 55, 19, 0.42))",
    steps: [
      "豆腐切块，平底锅两面煎至微黄。",
      "另起锅爆香蒜末和葱白，加入生抽、蚝油和少量水。",
      "放入豆腐小火焖 3 分钟，让味道渗入。",
      "最后淋入薄芡，撒大量葱花即可。"
    ],
    tips: "如果想更香，可以先用厨房纸吸掉豆腐表面水分再煎。"
  }
];
